---
- hosts: db
  become: true
  gather_facts: true
  vars_files: inventory/group_vars/all_vault.yml
  roles:
    - role: db
      tags: db

- hosts: frontend
  become: true
  gather_facts: false
  vars_files: inventory/group_vars/all_vault.yml
  roles:
    - role: frontend
      tags: frontend

- hosts: backend
  become: true
  gather_facts: true
  vars_files: inventory/group_vars/all_vault.yml
  roles:
    - role: backend
      tags: backend

- hosts: monitoring
  become: true
  gather_facts: true
  vars_files: inventory/group_vars/all_vault.yml
  roles:
    - role: monitoring
      tags: monitoring

- hosts: log
  become: true
  gather_facts: false
  vars_files: inventory/group_vars/all_vault.yml
  roles:
    - role: log
      tags: log
...
