---
- name: Create node exporter user
  user:
    name: node_exporter
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present
  tags: node_exporter

- name: Download node exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
  tags: node_exporter

- name: Unarchive node exporter
  unarchive:
    src: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
    remote_src: true
  tags: node_exporter

- name: Copy node_exporter binary file
  copy:
    src: "node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    mode: 0755
    remote_src: true
  tags: node_exporter

- name: Create node_exporter service
  copy:
    src: files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  tags: node_exporter

- name: Start node exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
  tags: node_exporter
