- name: Copy filebeat deb package
  copy:
    src: "files/filebeat-{{ elk_version }}-amd64.deb"
    dest: /home/vagrant
  tags: filebeat

- name: Install filebeat
  apt:
    deb: "/home/vagrant/filebeat-{{ elk_version }}-amd64.deb"
  tags: filebeat

- name: Copy filebeat config
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
  notify: Restart filebeat
  tags: filebeat

- name: Enable nginx module
  shell: filebeat modules enable nginx
  args:
    creates: /etc/filebeat/modules.d/nginx.yml
  notify: Restart filebeat
  tags: filebeat

- name: Copy filebeat nginx module config
  copy:
    src: files/nginx.yml
    dest: /etc/filebeat/modules.d/nginx.yml
    owner: root
    group: root
    mode: 0644
  notify: Restart filebeat
  tags: filebeat

- name: Restart filebeat
  meta: flush_handlers
  tags: filebeat

- name: Start filebeat service
  systemd:
    name: filebeat
    state: started
    enabled: true
  tags: filebeat
