---
# tasks file for monitoring
- name: Create group monitoring
  group:
    name: monitoring
    state: present
  tags:
   - prometheus
   - grafana
   - ssl

- name: Create folder fo ssl
  file:
    path: "/etc/ssl/{{ monitoring_srv }}"
    state: directory
    owner: root
    group: monitoring
    mode: 0750
  tags:
    - ssl

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/{{ monitoring_srv }}"
    owner: root
    group: monitoring
    mode: 0750
  with_items:
    - "files/certificates/{{ monitoring_srv }}/fullchain.pem"
    - "files/certificates/{{ monitoring_srv }}/privkey.pem"
  tags: ssl

- name: Configure prometheus
  import_tasks: prometheus.yml

- name: Configure grafana
  import_tasks: grafana.yml

- name: Configure alertmanager
  import_tasks: alertmanager.yml

- name: Configure node exporter
  import_tasks: node_exporter.yml

- name: Configure iptables
  import_tasks: iptables.yml
