- name: Create prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present
    groups: monitoring
    append: true
  tags: prometheus

- name: Create derectories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
  tags: prometheus

- name: Download prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
  tags: prometheus

- name: Unarchive prometheus
  unarchive:
    src: "prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
    remote_src: true
  tags: prometheus

- name: Copy prometheus binary files
  copy:
    src: "/home/vagrant/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: true
  with_items:
    - prometheus
    - promtool
  tags: prometheus

- name: Copy prometheus libraries
  copy:
    src: "/home/vagrant/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: true
  with_items:
    - consoles
    - console_libraries
  tags: prometheus

- name: Copy prometheus config files
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - prometheus.yml
    - web.yml
  notify: Restart prometheus
  tags: prometheus

- name: Copy prometheus recording rules file
  copy:
    src: files/mysql_exporter_recording_rules.yml
    dest: /etc/prometheus/mysql_exporter_recording_rules.yml
    owner: prometheus
    group: prometheus
    mode: 0755
  notify: Restart prometheus
  tags: prometheus

- name: Copy prometheus alert rules file
  copy:
    src: files/alert.rules.yml
    dest: /etc/prometheus/alert.rules.yml
    owner: prometheus
    group: prometheus
    mode: 0755
  notify: Restart prometheus
  tags: prometheus

- name: Create prometheus service
  copy:
    src: files/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  tags: prometheus

- name: Restart prometheus
  meta: flush_handlers
  tags: prometheus

- name: Start prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
  tags: prometheus
