---
# tasks file for db
- name: Install packages
  apt:
    name:
      - mysql-server
      - mysql-client
      - python3-pymysql
    state: present
    update_cache: true
  tags: mysql

- name: Restart mysql service
  systemd:
    name: mysql
    state: started
    enabled: true

- name: Copy mysqld config file
  template:
    src: templates/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mysql
  tags: mysql

- name: Restart mysql
  meta: flush_handlers
  tags: mysql

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    password: "{{ db_root_password }}"
    check_implicit_admin: true
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: mysql

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
  tags: mysql

- name: Create db user
  mysql_user:
    name: "{{ db_user }}"
    host: "%"
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
    priv: "{{ db_name }}.*:ALL"
  tags: mysql

- name: Create user for replication
  mysql_user:
    name: "{{ db_repl_user }}"
    host: '%'
    password: "{{ db_repl_password }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
    priv: '*.*:REPLICATION SLAVE'
  when: 'ansible_hostname == "db-master"'
  tags:
    - mysql
    - replciation

- name: Copy db dump to servers
  copy:
    src: files/wordpress.sql
    dest: /home/vagrant/wordpress.sql
  tags: replication

- name: Loading wordpress dump
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: wordpress
    state: import
    target: /home/vagrant/wordpress.sql
  tags:
    - mysql
    - replication

- name: Configure replication on slave
  mysql_replication:
    mode: changeprimary
    primary_host: "{{ db_master_srv }}"
    primary_port: 3306
    primary_user: "{{ db_repl_user }}"
    primary_password: "{{ db_repl_password }}"
    primary_auto_position: true
    login_user: root
    login_password: "{{ db_root_password }}"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Start replication
  mysql_replication:
    mode: startreplica
    login_user: root
    login_password: "{{ db_root_password }}"
  when: 'ansible_hostname == "db-slave"'
  tags:
    - mysql
    - replication

- name: Install node exporter
  include_tasks: node_exporter.yml

- name: Install mysqld exporter
  include_tasks: mysqld_exporter.yml
