- name: Create my.cnf for root
  copy:
    content: |
      [mysqldump]
      user=root
      password={{ db_root_password }}
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  notify: Restart mysql
  tags:
    - mysql
    - mysql_backup

- name: Set permissions to .my.cnf
  file:
    path: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  notify: Restart mysql
  tags:
    - mysql
    - mysql_backup

- name: Create folder for mysql backups
  file:
    path: /home/vagrant/mysql_backup
    state: directory
    owner: vagrant
    group: root
    mode: 0775
  when: 'ansible_hostname == "db-slave"'
  tags: mysql_backup

- name: Create systemd service and timer for mysqld backup
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mysql_backup.service
    - mysql_backup.timer
  when: 'ansible_hostname == "db-slave"'
  tags: mysql_backup

- name: Start mysql backup timer
  systemd:
    name: mysql_backup.timer
    state: started
    enabled: true
    daemon_reload: true
  when: 'ansible_hostname == "db-slave"'
  tags: mysql_backup
