- name: Create mysqld_exporter user
  user:
    name: mysqld_exporter
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present
  tags: mysqld_exporter

- name: Download mysqld exporter
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysql_exporter_version }}/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
  tags: mysqld_exporter

- name: Unarchive mysqld exporter
  unarchive:
    src: "mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz"
    dest: /home/vagrant
    remote_src: true
  tags: mysqld_exporter

- name: Copy mysqld exporter binary file
  copy:
    src: "mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64/mysqld_exporter"
    dest: /usr/local/bin
    owner: mysqld_exporter
    group: mysqld_exporter
    mode: 0755
    remote_src: true
  notify: Restart mysqld_exporter
  tags: mysqld_exporter

- name: Create folder for mysqld_exporter config
  file:
    path: /etc/mysqld_exporter
    state: directory
    owner: mysqld_exporter
    group: mysqld_exporter
    mode: 0755
  tags: mysqld_exporter

- name: Copy mysqld_exporter my.cnf config
  template:
    src: templates/mysqld_exporter.my.cnf.j2
    dest: /etc/mysqld_exporter/.my.cnf
    owner: mysqld_exporter
    group: mysqld_exporter
    mode: 0600
  notify: Restart mysqld_exporter
  tags: mysqld_exporter

- name: Create mysqld_exporter service
  template:
    src: templates/mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: Restart mysqld_exporter
  tags: mysqld_exporter

- name: Create db user for mysqld_exporter
  mysql_user:
    name: "{{ db_mysqld_exporter_user }}"
    host: 'localhost'
    password: "{{ db_mysqld_exporter_password }}"
    login_user: root
    login_password: "{{ db_root_password }}"
    state: present
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
  tags: mysqld_exporter

- name: Start mysqld exporter service
  systemd:
    name: mysqld_exporter
    state: started
    enabled: true
    daemon_reload: true
  tags: mysqld_exporter
